### ISSUE TITLE
Install THREDDS on gamone with access on port 80

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#223]
Let's get THREDDS installed on gamone using Docker and NGINX to do the forwarding from 80 to 8080

**Comment by rsignell-usgs** [comment]
```
sudo docker run -d --name tds -p 8080:8080 axiom/docker-thredds


sudo docker pull axiom/docker-thredds:5.0


sudo docker run -d -p 8080:8080 -p 8443:8443 -v /opt/docker/usgs-dev/tomcat-thredds:/opt/tomcat/content/thredds -v /opt/docker/usgs-dev/tomcat-thredds/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml -v /usgs:/usgs -v /clay/usgs:/clay/usgs --name tds-dev   axiom/docker-thredds:5.0

 docker inspect -f "{{ .Mounts }}" tds-dev

sudo docker run -d --name nginx -p 80:80 -v ~/docker-nginx/html:/usr/share/nginx/html  -v /etc/nginx/conf.d:/etc/nginx/conf.d nginx

sudo docker cp nginx:/etc/nginx/conf.d/default.conf default.conf

cd /etc/nginx


```

**Comment by rsignell-usgs** [comment]
This is now working, using NGINX as above and docker-compose.yml:
```
ssh rsignell@gamone.whoi.edu
cd /opt/docker
more docker-compose.yml

###
# tds-dev:  THREDDS Data Server- Development
###
tds-dev:
  image: unidata/thredds-docker:5.0-SNAPSHOT
  ports:
    - "8080:8080"
    - "8443:8443"
  container_name: tds-dev
  volumes:
    - /opt/docker/tds-dev/tomcat/logs/:/usr/local/tomcat/logs/
    - /opt/docker/tds-dev/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
    - /opt/docker/tds-dev/tomcat/conf/tomcat-users.xml:/usr/local/tomcat/conf/to
mcat-users.xml
    - /opt/docker/tds-dev/thredds/:/usr/local/tomcat/content/thredds
    - /usgs:/usgs:ro
    - /sand/usgs:/sand/usgs:ro
#    - /clay/usgs:/clay/usgs:ro
```
